import type { CodeCategory } from '../../src/modules/settings/master-data.service.js';

/** Initial master data (BO-32); maintained by administrators afterwards. */
export const CODES: Record<CodeCategory, [code: string, label: string][]> = {
  DOCUMENT_TYPE: [
    ['PROPOSAL_FORM', 'Proposal form'],
    ['PDS', 'Product disclosure sheet'],
    ['IC_COPY', 'IC copy'],
    ['PASSPORT_COPY', 'Passport copy'],
    ['HP_APPROVAL_LETTER', 'Hire purchase approval letter'],
    ['HP_STATEMENT', 'Hire purchase statement (existing financing)'],
    ['FINANCING_APPROVAL_LETTER', 'Financing approval letter'],
    ['DRAWDOWN_LETTER', 'Drawdown letter'],
    ['QUESTIONNAIRE', 'Signed questionnaire'],
    ['NOMINEE_IC', 'IC copy of nominee / beneficiary / executor'],
    ['EMPLOYER_IC', 'Employer IC copy'],
    ['EMPLOYEE_IC', 'Domestic helper IC copy'],
    ['EMPLOYEE_DETAILS', 'Domestic helper employment details'],
    ['LABOUR_LICENCE', 'Labour licence copy'],
    ['STUDENT_ID', 'Student ID / offer letter'],
    ['SIGNED_PROPOSAL_FORM', 'Signed proposal form'],
    ['SIGNATURE_AGENT', 'Agent signature'],
    ['SIGNATURE_PARTICIPANT', 'Participant signature'],
    ['PAYMENT_PROOF', 'Proof of payment'],
    ['CLAIM_FORM', 'Claim form'],
    ['CLAIM_SUPPORT', 'Claim supporting document'],
    ['AGENT_LICENCE', 'Agent registration / licence'],
    ['PHOTO', 'Passport photograph'],
    ['BANK_AUTHORISATION', 'Bank authorisation letter'],
    ['SCREENSHOT', 'Screenshot'],
    ['OTHER', 'Other document'],
    ['POLICY_SCHEDULE', 'e-Policy schedule'],
    ['RECEIPT', 'e-Receipt'],
    ['EOD_REPORT', 'End-of-day report'],
    ['FIN_FILE', 'FIN interface file'],
    ['SCHEDULED_REPORT', 'Scheduled report'],
  ],
  RELATIONSHIP: [
    ['SPOUSE', 'Spouse'],
    ['CHILD', 'Child'],
    ['PARENT', 'Parent'],
    ['SIBLING', 'Sibling'],
    ['OTHER_RELATIVE', 'Other relative'],
    ['EXECUTOR', 'Executor'],
    ['OTHER', 'Other'],
  ],
  NATIONALITY: [
    ['BRUNEI', 'Brunei Darussalam'],
    ['MALAYSIA', 'Malaysia'],
    ['INDONESIA', 'Indonesia'],
    ['PHILIPPINES', 'Philippines'],
    ['INDIA', 'India'],
    ['BANGLADESH', 'Bangladesh'],
    ['OTHER', 'Other'],
  ],
  DISTRICT: [
    ['BRUNEI_MUARA', 'Brunei-Muara'],
    ['TUTONG', 'Tutong'],
    ['BELAIT', 'Belait'],
    ['TEMBURONG', 'Temburong'],
  ],
  BANK: [
    ['BANK_A', 'Partner bank A'],
    ['BANK_B', 'Partner bank B'],
    ['OTHER', 'Other bank'],
  ],
  OCCUPATION: [
    ['PROFESSIONAL', 'Professional'],
    ['MANAGERIAL', 'Managerial'],
    ['EXECUTIVE', 'Executive'],
    ['ADMINISTRATIVE', 'Administrative'],
    ['CLERICAL', 'Clerical'],
    ['TECHNICAL', 'Technical'],
    ['SKILLED_MANUAL', 'Skilled manual'],
    ['STUDENT', 'Student'],
    ['HOMEMAKER', 'Homemaker'],
    ['RETIRED', 'Retired'],
    ['OTHER', 'Other'],
  ],
  CLAIM_TYPE: [
    ['DEATH', 'Death'],
    ['TPD', 'Total and permanent disability'],
    ['ACCIDENT', 'Accidental injury'],
    ['MEDICAL', 'Medical / hospitalisation'],
    ['REPATRIATION', 'Repatriation'],
    ['OTHER', 'Other'],
  ],
  ISSUE_CATEGORY: [
    ['LOGIN_ACCESS', 'Login and access'],
    ['QUOTATION_POLICY', 'Quotation / policy'],
    ['PAYMENT', 'Payment and receipts'],
    ['DOCUMENTS', 'Documents'],
    ['REPORTS', 'Reports'],
    ['SYSTEM_ERROR', 'System error'],
    ['OTHER', 'Other'],
  ],
  ENDORSEMENT_TYPE: [
    ['NOMINEE_CHANGE', 'Change of nominee / beneficiary'],
    ['CORRECTION', 'Correction of particulars'],
    ['CONTACT_DETAILS', 'Change of contact details'],
    ['OTHER', 'Other'],
  ],
  CANCELLATION_REASON: [
    ['FULL_SETTLEMENT', 'Financing fully settled'],
    ['PARTICIPANT_REQUEST', 'Participant request'],
    ['DUPLICATE', 'Duplicate policy'],
    ['NON_PAYMENT', 'Non-payment of contribution'],
    ['OTHER', 'Other'],
  ],
};
