import type { ParameterType } from '../../generated/prisma/enums.js';

/**
 * Business parameters maintainable by administrators without code changes (BO-33, COM-09).
 * Defaults are seeded on first start-up; administrators change values in the Back-office.
 */
export const Setting = {
  PasswordMinLength: 'security.password.min_length',
  PasswordRequireUpper: 'security.password.require_upper',
  PasswordRequireLower: 'security.password.require_lower',
  PasswordRequireDigit: 'security.password.require_digit',
  PasswordRequireSymbol: 'security.password.require_symbol',
  PasswordHistoryCount: 'security.password.history_count',
  PasswordExpiryDays: 'security.password.expiry_days',
  LockoutMaxAttempts: 'security.lockout.max_attempts',
  LockoutMinutes: 'security.lockout.minutes',
  SessionIdleMinutes: 'security.session.idle_minutes',
  SessionAbsoluteHours: 'security.session.absolute_hours',
  SessionSingleActive: 'security.session.single_active',
  PaymentGraceDays: 'billing.payment_grace_days',
  QuotationValidityDays: 'policy.quotation_validity_days',
  RenewalNoticeDays: 'policy.renewal_notice_days',
  RequireParticipantSignature: 'policy.require_participant_signature',
  ESignLinkHours: 'policy.esign_link_hours',
  AmlMatchThreshold: 'aml.match_threshold',
  DefaultCommissionRate: 'commission.default_rate',
  SlaCriticalResponseHours: 'sla.critical.response_hours',
  SlaCriticalResolutionHours: 'sla.critical.resolution_hours',
  SlaHighResponseHours: 'sla.high.response_hours',
  SlaHighResolutionHours: 'sla.high.resolution_hours',
  SlaMediumResponseHours: 'sla.medium.response_hours',
  SlaMediumResolutionHours: 'sla.medium.resolution_hours',
  SlaLowResponseHours: 'sla.low.response_hours',
  SlaLowResolutionHours: 'sla.low.resolution_hours',
  IntegrationMaxAttempts: 'integration.max_attempts',
  NotificationMaxAttempts: 'notification.max_attempts',
  DocumentExpiryWarningDays: 'document.expiry_warning_days',
} as const;

export type SettingKey = (typeof Setting)[keyof typeof Setting];

export interface SettingDefault {
  key: SettingKey;
  value: string;
  valueType: ParameterType;
  category: string;
  description: string;
  min?: number;
  max?: number;
}

export const SETTING_DEFAULTS: SettingDefault[] = [
  {
    key: Setting.PasswordMinLength,
    value: '12',
    valueType: 'INTEGER',
    category: 'Security',
    description: 'Minimum password length',
    min: 8,
    max: 64,
  },
  {
    key: Setting.PasswordRequireUpper,
    value: 'true',
    valueType: 'BOOLEAN',
    category: 'Security',
    description: 'Password must contain an upper-case letter',
  },
  {
    key: Setting.PasswordRequireLower,
    value: 'true',
    valueType: 'BOOLEAN',
    category: 'Security',
    description: 'Password must contain a lower-case letter',
  },
  {
    key: Setting.PasswordRequireDigit,
    value: 'true',
    valueType: 'BOOLEAN',
    category: 'Security',
    description: 'Password must contain a digit',
  },
  {
    key: Setting.PasswordRequireSymbol,
    value: 'true',
    valueType: 'BOOLEAN',
    category: 'Security',
    description: 'Password must contain a symbol',
  },
  {
    key: Setting.PasswordHistoryCount,
    value: '5',
    valueType: 'INTEGER',
    category: 'Security',
    description: 'Number of previous passwords that cannot be reused',
    min: 0,
    max: 24,
  },
  {
    key: Setting.PasswordExpiryDays,
    value: '90',
    valueType: 'INTEGER',
    category: 'Security',
    description: 'Days before a password must be changed (0 = never)',
    min: 0,
    max: 365,
  },
  {
    key: Setting.LockoutMaxAttempts,
    value: '5',
    valueType: 'INTEGER',
    category: 'Security',
    description: 'Failed login attempts before the account is locked',
    min: 3,
    max: 20,
  },
  {
    key: Setting.LockoutMinutes,
    value: '30',
    valueType: 'INTEGER',
    category: 'Security',
    description: 'Lock duration in minutes (administrator can unlock earlier)',
    min: 1,
    max: 1440,
  },
  {
    key: Setting.SessionIdleMinutes,
    value: '15',
    valueType: 'INTEGER',
    category: 'Security',
    description: 'Session idle timeout in minutes',
    min: 5,
    max: 120,
  },
  {
    key: Setting.SessionAbsoluteHours,
    value: '8',
    valueType: 'INTEGER',
    category: 'Security',
    description: 'Maximum session lifetime in hours',
    min: 1,
    max: 24,
  },
  {
    key: Setting.SessionSingleActive,
    value: 'true',
    valueType: 'BOOLEAN',
    category: 'Security',
    description: "Signing in ends the user's other sessions",
  },
  {
    key: Setting.PaymentGraceDays,
    value: '7',
    valueType: 'INTEGER',
    category: 'Billing',
    description:
      'Days after issuance within which contribution must be submitted before the agency is blocked',
    min: 1,
    max: 60,
  },
  {
    key: Setting.QuotationValidityDays,
    value: '30',
    valueType: 'INTEGER',
    category: 'Policy',
    description: 'Days a draft quotation remains valid',
    min: 1,
    max: 180,
  },
  {
    key: Setting.RenewalNoticeDays,
    value: '45',
    valueType: 'INTEGER',
    category: 'Policy',
    description: 'Days before expiry that a policy is listed as due for renewal',
    min: 7,
    max: 120,
  },
  {
    key: Setting.RequireParticipantSignature,
    value: 'true',
    valueType: 'BOOLEAN',
    category: 'Policy',
    description: 'Participant signature is mandatory before submission',
  },
  {
    key: Setting.ESignLinkHours,
    value: '72',
    valueType: 'INTEGER',
    category: 'Policy',
    description: 'Validity of e-signature links sent by email (hours)',
    min: 1,
    max: 336,
  },
  {
    key: Setting.AmlMatchThreshold,
    value: '85',
    valueType: 'INTEGER',
    category: 'Compliance',
    description: 'Name-match score (0-100) at or above which a screening is flagged for review',
    min: 50,
    max: 100,
  },
  {
    key: Setting.DefaultCommissionRate,
    value: '0.10',
    valueType: 'DECIMAL',
    category: 'Commission',
    description: 'Default commission / referral fee rate when the product does not define one',
    min: 0,
    max: 1,
  },
  {
    key: Setting.SlaCriticalResponseHours,
    value: '1',
    valueType: 'INTEGER',
    category: 'Issue SLA',
    description: 'Critical issue response target (hours)',
    min: 1,
    max: 72,
  },
  {
    key: Setting.SlaCriticalResolutionHours,
    value: '4',
    valueType: 'INTEGER',
    category: 'Issue SLA',
    description: 'Critical issue resolution target (hours)',
    min: 1,
    max: 168,
  },
  {
    key: Setting.SlaHighResponseHours,
    value: '2',
    valueType: 'INTEGER',
    category: 'Issue SLA',
    description: 'High issue response target (hours)',
    min: 1,
    max: 72,
  },
  {
    key: Setting.SlaHighResolutionHours,
    value: '24',
    valueType: 'INTEGER',
    category: 'Issue SLA',
    description: 'High issue resolution target (hours)',
    min: 1,
    max: 336,
  },
  {
    key: Setting.SlaMediumResponseHours,
    value: '8',
    valueType: 'INTEGER',
    category: 'Issue SLA',
    description: 'Medium issue response target (hours)',
    min: 1,
    max: 168,
  },
  {
    key: Setting.SlaMediumResolutionHours,
    value: '72',
    valueType: 'INTEGER',
    category: 'Issue SLA',
    description: 'Medium issue resolution target (hours)',
    min: 1,
    max: 720,
  },
  {
    key: Setting.SlaLowResponseHours,
    value: '24',
    valueType: 'INTEGER',
    category: 'Issue SLA',
    description: 'Low issue response target (hours)',
    min: 1,
    max: 336,
  },
  {
    key: Setting.SlaLowResolutionHours,
    value: '168',
    valueType: 'INTEGER',
    category: 'Issue SLA',
    description: 'Low issue resolution target (hours)',
    min: 1,
    max: 2160,
  },
  {
    key: Setting.IntegrationMaxAttempts,
    value: '6',
    valueType: 'INTEGER',
    category: 'Integration',
    description: 'Delivery attempts before an integration message is moved to dead-letter',
    min: 1,
    max: 20,
  },
  {
    key: Setting.NotificationMaxAttempts,
    value: '5',
    valueType: 'INTEGER',
    category: 'Notification',
    description: 'Email/SMS delivery attempts before giving up',
    min: 1,
    max: 20,
  },
  {
    key: Setting.DocumentExpiryWarningDays,
    value: '30',
    valueType: 'INTEGER',
    category: 'Documents',
    description: 'Days before expiry that documents are flagged',
    min: 1,
    max: 180,
  },
];
