/** Permission codes granted by the API (mirrors the server-side catalogue). */
export const P = {
  portalDashboard: 'portal.dashboard',
  portalProfileView: 'portal.profile.view',
  portalProfileUpdate: 'portal.profile.update',
  portalHierarchyView: 'portal.hierarchy.view',
  portalAgentRegister: 'portal.agents.register',
  portalAgencyWideView: 'portal.agency.view_all',
  portalParticipantsView: 'portal.participants.view',
  portalParticipantsManage: 'portal.participants.manage',
  portalPoliciesView: 'portal.policies.view',
  portalPoliciesQuote: 'portal.policies.quote',
  portalPoliciesSubmit: 'portal.policies.submit',
  portalPoliciesService: 'portal.policies.service',
  portalBillingView: 'portal.billing.view',
  portalBillingSubmit: 'portal.billing.submit',
  portalClaimsView: 'portal.claims.view',
  portalClaimsSubmit: 'portal.claims.submit',
  portalIssues: 'portal.issues',
  portalReports: 'portal.reports',
  portalCommissionView: 'portal.commission.view',

  boDashboard: 'bo.dashboard',
  boManagementDashboard: 'bo.dashboard.management',
  boUsersManage: 'bo.users.manage',
  boRolesManage: 'bo.roles.manage',
  boAgenciesView: 'bo.agencies.view',
  boAgenciesManage: 'bo.agencies.manage',
  boAgentsView: 'bo.agents.view',
  boAgentsManage: 'bo.agents.manage',
  boParticipantsView: 'bo.participants.view',
  boPoliciesView: 'bo.policies.view',
  boPaymentsView: 'bo.payments.view',
  boClaimsManage: 'bo.claims.manage',
  boDocumentsVerify: 'bo.documents.verify',
  boAmlReview: 'bo.aml.review',
  boApproveAgents: 'bo.approve.agents',
  boApproveParticipants: 'bo.approve.participants',
  boApprovePolicies: 'bo.approve.policies',
  boApproveServicing: 'bo.approve.servicing',
  boApprovePayments: 'bo.approve.payments',
  boWorkflowConfigure: 'bo.workflow.configure',
  boProductsManage: 'bo.products.manage',
  boIssuesManage: 'bo.issues.manage',
  boReportsView: 'bo.reports.view',
  boReportsSchedule: 'bo.reports.schedule',
  boAuditView: 'bo.audit.view',
  boConfigManage: 'bo.config.manage',
  boIntegrationManage: 'bo.integration.manage',
  boEodRun: 'bo.eod.run',
} as const;

export const APPROVE_PERMISSIONS = [
  P.boApproveAgents,
  P.boApproveParticipants,
  P.boApprovePolicies,
  P.boApproveServicing,
  P.boApprovePayments,
];
