/** Colour of each status value in tags, kept in one place so screens are consistent. */
const STATUS_COLOURS: Record<string, string> = {
  DRAFT: 'default',
  PENDING: 'gold',
  PENDING_APPROVAL: 'gold',
  PENDING_PAYMENT: 'orange',
  PENDING_VERIFICATION: 'orange',
  PENDING_REVIEW: 'orange',
  SUBMITTED: 'blue',
  UNDER_REVIEW: 'gold',
  ASSIGNED: 'blue',
  IN_PROGRESS: 'blue',
  OPEN: 'blue',
  ACTIVE: 'green',
  APPROVED: 'green',
  VERIFIED: 'green',
  PAID: 'green',
  CLEAR: 'green',
  CLEARED: 'green',
  AUTO_CLEARED: 'green',
  ACKNOWLEDGED: 'green',
  RESOLVED: 'green',
  COMPLETED: 'green',
  MATCHED: 'green',
  SENT: 'green',
  UPLOADED: 'blue',
  UNPAID: 'volcano',
  REJECTED: 'red',
  CONFIRMED_MATCH: 'red',
  FLAGGED: 'red',
  FAILED: 'red',
  DEAD: 'red',
  MISMATCH: 'red',
  SUSPENDED: 'red',
  TERMINATED: 'default',
  INACTIVE: 'default',
  EXPIRED: 'default',
  CANCELLED: 'default',
  WITHDRAWN: 'default',
  CLOSED: 'default',
  NOT_SCREENED: 'default',
  RUNNING: 'processing',
  CRITICAL: 'red',
  HIGH: 'volcano',
  MEDIUM: 'gold',
  LOW: 'default',
};

export function statusColour(status: string | null | undefined): string {
  return (status && STATUS_COLOURS[status]) || 'default';
}
